# Generated by Django 3.2.10 on 2023-05-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='seller',
            field=models.BooleanField(default=False, max_length=50, verbose_name='Продавец'),
        ),
    ]
