# Generated by Django 3.2.10 on 2023-05-02 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_customuser_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Категория продукта')),
                ('bank_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='seller',
            field=models.BooleanField(default=False, help_text='По умолчанию не Продавец', max_length=50, verbose_name='Продавец'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('product_description', models.CharField(blank=True, max_length=200, null=True, verbose_name=' Описание')),
                ('price_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='price.category')),
            ],
            options={
                'verbose_name': 'products',
                'verbose_name_plural': 'products',
                'permissions': [('add_Product', 'Can add Product')],
            },
        ),
    ]
