# Generated by Django 3.2.10 on 2023-05-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_auto_20230502_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_value_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
