# Generated by Django 3.2.10 on 2023-05-05 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0007_auto_20230505_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_value_total',
        ),
    ]
