# Generated by Django 3.2.10 on 2023-05-05 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0009_auto_20230505_0343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'permissions': [('add_Product', 'Can add Product')], 'verbose_name': 'Цена', 'verbose_name_plural': 'Цена'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('add_Product', 'Can add Product')], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
