# Generated by Django 3.2.10 on 2023-05-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0011_alter_customuser_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='seller',
            field=models.BooleanField(blank=True, help_text='По умолчанию не Продавец', max_length=50, null=True, verbose_name='Продавец'),
        ),
    ]
